### ISSUE TITLE
Unable to apply custom styles

### ISSUE THREAD

**Issue by AngularTurkiye** [cipchk/ngx-countdown#6]
Hello,

Thanks for the plugin. Due to building issues, we are using 1.0.2. In this version, we are unable to apply custom styling.

Had to comment out styling from component.js > line 203. Can you please remove styling or update code so we can apply custom styles.

Thanks.

**Comment by cipchk** [comment]
now `1.0.4` version compatible angular4 & 5, have any reason not to using laster version?

**Comment by AngularTurkiye** [comment]
Unable build with angular 4.3.6, are you sure it works with 4.x?

**Comment by cipchk** [comment]
how custom styling in `1.0.2`?

html:

```html
<countdown class="laster"></countdown>
```

scss:

```scss
:host {
    ::ng-deep {
        .count-down .digital {
            color: #000;
        }
   }
}
```

do you think?
